// ============================================================
//  data.js – Sapporo Travel Guide  (A Guide to Sapporo)
// ============================================================

const CATEGORIES = [
  {
    id: 'ramen',
    name: 'ラーメン',
    icon: '🍜',
    color: '#c0392b',
    description: '札幌を代表するソウルフード。濃厚な味噌スープが絶品！',
    featured: true,
  },
  {
    id: 'jingisukan',
    name: 'ジンギスカン',
    icon: '🥩',
    color: '#922b21',
    description: '北海道を代表するラム肉の焼肉料理。豪快に食べよう！',
    featured: true,
  },
  {
    id: 'seafood',
    name: '海鮮・寿司',
    icon: '🦀',
    color: '#d35400',
    description: '日本最北の大地が育む新鮮な海の幸を堪能。',
    featured: true,
  },
  {
    id: 'soup-curry',
    name: 'スープカレー',
    icon: '🍛',
    color: '#e67e22',
    description: '札幌生まれのご当地グルメ。具だくさんのスパイシースープ。',
    featured: false,
  },
  {
    id: 'gourmet',
    name: 'その他グルメ',
    icon: '🍽️',
    color: '#e74c3c',
    description: '朝食・ランチ・ディナーに訪れたい名店をご紹介。',
    featured: false,
  },
  {
    id: 'cafe',
    name: 'カフェ',
    icon: '☕',
    color: '#6f4e37',
    description: '札幌の個性豊かなカフェで、こだわりの一杯を。',
    featured: false,
  },
  {
    id: 'sweets-western',
    name: '洋菓子店',
    icon: '🍰',
    color: '#ad1457',
    description: '北海道産の乳製品・小麦を活かした絶品スイーツ。',
    featured: false,
  },
  {
    id: 'sweets-japanese',
    name: '和菓子店',
    icon: '🍡',
    color: '#bf360c',
    description: '季節の和菓子と上質なひと時を。',
    featured: false,
  },
  {
    id: 'crafts',
    name: '工芸品・お土産',
    icon: '🏺',
    color: '#4e342e',
    description: '北海道の職人技が光る工芸品・ユニークなお土産。',
    featured: false,
  },
  {
    id: 'unique-shops',
    name: 'ユニークショップ',
    icon: '🏪',
    color: '#37474f',
    description: '個性的な専門店・一度は訪れたい話題のお店。',
    featured: false,
  },
  {
    id: 'sightseeing',
    name: '観光スポット',
    icon: '🏔️',
    color: '#2e7d32',
    description: '初めての札幌で絶対に外せない名所・旧跡。',
    featured: false,
  },
  {
    id: 'onsen',
    name: '温泉',
    icon: '♨️',
    color: '#1565c0',
    description: '旅の疲れを癒す、札幌周辺の名湯。',
    featured: false,
  },
  {
    id: 'amusement',
    name: 'アミューズメント',
    icon: '🎡',
    color: '#e65100',
    description: '大人も子どもも楽しめる体験・施設。',
    featured: false,
  },
  {
    id: 'accommodation',
    name: '宿泊施設',
    icon: '🏨',
    color: '#006064',
    description: '快適な滞在のためのホテル・旅館ガイド。',
    featured: false,
  },
  {
    id: 'events',
    name: '季節のイベント',
    icon: '🎉',
    color: '#4a148c',
    description: '一年を通して楽しめる、札幌の祭り・イベント。',
    featured: false,
  },
];

const PLACES = [
  // ===== RAMEN =====
  {
    id: 'r1',
    category: 'ramen',
    name: '麺屋 彩未',
    nameEn: 'Menya Saimi',
    description: '濃厚でコクのある味噌ラーメンの名店。行列必至の人気店で、丁寧に作られたスープと縮れ麺の相性が抜群。',
    address: '札幌市豊平区美園10条5丁目3-12',
    nearest: '地下鉄東豊線「美園」駅',
    hours: '11:00〜15:30',
    closed: '月曜・火曜',
    budget: '〜1,000円',
    rating: 5,
    tags: ['味噌ラーメン', '行列', 'ランチ'],
    mapQuery: '麺屋彩未 札幌',
    featured: true,
    highlight: '札幌味噌ラーメンの最高峰',
  },
  {
    id: 'r2',
    category: 'ramen',
    name: '一幻',
    nameEn: 'Ichigen',
    description: '北海道産の甘えびを贅沢に使ったえびそばの専門店。えびの旨味が凝縮された濃厚スープが病みつきになる。',
    address: '札幌市中央区南7条西9丁目1024-10',
    nearest: '地下鉄南北線「中島公園」駅',
    hours: '11:00〜翌3:00',
    closed: '不定休',
    budget: '〜1,500円',
    rating: 4,
    tags: ['えびそば', '甘えび', '深夜営業'],
    mapQuery: '一幻 札幌 えびそば',
    featured: true,
    highlight: '甘えびの旨味たっぷり',
  },
  {
    id: 'r3',
    category: 'ramen',
    name: '純連（すみれ）',
    nameEn: 'Sumire',
    description: '豚骨ベースの濃厚な味噌ラーメン。ラードの膜が熱さを保つ伝統的な札幌スタイルを守り続ける老舗。',
    address: '札幌市中央区南6条西3丁目 すすきのラフィラB1F',
    nearest: '地下鉄南北線「すすきの」駅',
    hours: '11:00〜22:00',
    closed: '年中無休',
    budget: '〜1,000円',
    rating: 4,
    tags: ['味噌ラーメン', '老舗', 'すすきの'],
    mapQuery: '純連 すみれ 札幌',
    featured: false,
  },
  {
    id: 'r4',
    category: 'ramen',
    name: '山頭火',
    nameEn: 'Santouka',
    description: '旭川発祥の塩ラーメン専門店。透き通った清澄なスープと細いストレート麺が絶妙なバランス。',
    address: '札幌市中央区大通西2丁目 クリスタルホール地下2F',
    nearest: '地下鉄東西線「大通」駅',
    hours: '11:00〜21:30',
    closed: '年中無休',
    budget: '〜1,000円',
    rating: 4,
    tags: ['塩ラーメン', '旭川', 'クリア'],
    mapQuery: '山頭火 札幌 大通',
    featured: false,
  },
  {
    id: 'r5',
    category: 'ramen',
    name: '札幌ラーメン共和国',
    nameEn: 'Sapporo Ramen Republic',
    description: 'JRタワー10Fにある8店舗が集まるラーメンテーマパーク。昭和の街並みを再現した空間で、北海道中のラーメンを食べ比べ。',
    address: '札幌市中央区北5条西2丁目 JRタワーステラプレイス10F',
    nearest: 'JR「札幌」駅直結',
    hours: '11:00〜22:00',
    closed: '年中無休',
    budget: '〜1,500円',
    rating: 4,
    tags: ['テーマパーク', '食べ比べ', 'JRタワー', '観光'],
    mapQuery: '札幌ラーメン共和国',
    featured: false,
    highlight: '8つの名店が集結',
  },
  {
    id: 'r6',
    category: 'ramen',
    name: '白樺山荘',
    nameEn: 'Shirakaba Sansou',
    description: '豚骨と魚介のダブルスープが特徴の中太縮れ麺。バターコーンのトッピングが人気。昭和の雰囲気漂う老舗。',
    address: '札幌市中央区南1条西5丁目',
    nearest: '地下鉄東西線「大通」駅',
    hours: '11:00〜翌1:00',
    closed: '不定休',
    budget: '〜1,000円',
    rating: 3,
    tags: ['バターコーン', '老舗', '夜遅くまで'],
    mapQuery: '白樺山荘 ラーメン 札幌',
    featured: false,
  },

  // ===== JINGISUKAN =====
  {
    id: 'j1',
    category: 'jingisukan',
    name: 'だるま',
    nameEn: 'Daruma',
    description: '昭和28年創業のジンギスカンの老舗。すすきのに複数店舗を構え、国産ラム肉を直火で豪快に焼く。行列覚悟の超人気店。',
    address: '札幌市中央区南5条西4丁目（本店）',
    nearest: '地下鉄南北線「すすきの」駅',
    hours: '17:00〜翌3:00',
    closed: '年中無休',
    budget: '3,000〜5,000円',
    rating: 5,
    tags: ['老舗', 'すすきの', '行列', '生ラム'],
    mapQuery: 'だるま ジンギスカン 札幌',
    featured: true,
    highlight: '70年以上愛される名店',
  },
  {
    id: 'j2',
    category: 'jingisukan',
    name: 'しろくま',
    nameEn: 'Shirokuma',
    description: '大通公園エリアの人気ジンギスカン店。新鮮なラム肉と野菜をセットで注文できる。ランチも営業しているので昼間でも楽しめる。',
    address: '札幌市中央区南2条西5丁目 第二三谷ビル2F',
    nearest: '地下鉄東西線「大通」駅',
    hours: '11:30〜14:30、17:00〜22:30',
    closed: '不定休',
    budget: '2,000〜4,000円',
    rating: 4,
    tags: ['大通', 'ランチ', 'ラム肉'],
    mapQuery: 'しろくま ジンギスカン 札幌',
    featured: false,
  },
  {
    id: 'j3',
    category: 'jingisukan',
    name: 'まつじん',
    nameEn: 'Matsujin',
    description: '国産羊肉にこだわったジンギスカン専門店。特製のタレが肉の旨味を引き立てる。創業50年以上の確かな技。',
    address: '札幌市中央区南5条西5丁目 狸小路5丁目',
    nearest: '地下鉄南北線「すすきの」駅',
    hours: '17:00〜23:00',
    closed: '水曜',
    budget: '3,000〜5,000円',
    rating: 4,
    tags: ['国産羊肉', '老舗', '狸小路'],
    mapQuery: 'まつじん ジンギスカン 札幌',
    featured: false,
  },
  {
    id: 'j4',
    category: 'jingisukan',
    name: 'サッポロビール園',
    nameEn: 'Sapporo Beer Garden',
    description: '明治時代の赤レンガ工場を活かしたビール園。ジンギスカンと黒ラベル生ビールの組み合わせは北海道観光の定番！',
    address: '札幌市東区北7条東9丁目2-10',
    nearest: 'JR「札幌」駅からシャトルバスあり',
    hours: '11:30〜21:30（LO 20:30）',
    closed: '不定休',
    budget: '3,000〜5,000円',
    rating: 4,
    tags: ['ビール', '赤レンガ', '観光', '定番'],
    mapQuery: 'サッポロビール園 札幌',
    featured: true,
    highlight: '明治の赤レンガでビールとジンギスカン',
  },
  {
    id: 'j5',
    category: 'jingisukan',
    name: '羊屋',
    nameEn: 'Hitsuji-ya',
    description: '道内の牧場から仕入れる厳選ラム肉を使用。塩・タレ・スパイスで様々な楽しみ方ができるモダンなジンギスカン店。',
    address: '札幌市中央区南3条西6丁目 たぬきビル2F',
    nearest: '地下鉄東西線「大通」駅',
    hours: '17:00〜23:00',
    closed: '月曜',
    budget: '3,000〜6,000円',
    rating: 4,
    tags: ['厳選ラム', 'モダン', 'ワイン'],
    mapQuery: '羊屋 ジンギスカン 札幌',
    featured: false,
  },

  // ===== SEAFOOD =====
  {
    id: 's1',
    category: 'seafood',
    name: '二条市場',
    nameEn: 'Nijo Market',
    description: '150年以上の歴史を誇る市場。新鮮な海産物・農産物が並び、朝食から食べ歩きまで楽しめる。毛ガニ・ウニ・イクラが人気。',
    address: '札幌市中央区南3条東1・2丁目',
    nearest: '地下鉄東西線「バスセンター前」駅',
    hours: '7:00〜18:00（店舗により異なる）',
    closed: '不定休',
    budget: '〜3,000円',
    rating: 4,
    tags: ['朝市', '毛ガニ', 'ウニ', '観光', '食べ歩き'],
    mapQuery: '二条市場 札幌',
    featured: true,
    highlight: '150年の歴史！朝の定番スポット',
  },
  {
    id: 's2',
    category: 'seafood',
    name: '回転寿司 根室花まる',
    nameEn: 'Nemuro Hanamaru Kaiten Sushi',
    description: '根室から直送される新鮮なネタが自慢の回転寿司。ウニ・ホタテ・サーモンなど北海道ならではのネタが豊富。行列必至の人気店。',
    address: '札幌市中央区北5条西2丁目 JRタワーステラプレイス6F',
    nearest: 'JR「札幌」駅直結',
    hours: '11:00〜22:00（LO 21:30）',
    closed: '年中無休',
    budget: '1,500〜4,000円',
    rating: 5,
    tags: ['回転寿司', 'ウニ', 'ホタテ', '行列', 'JRタワー'],
    mapQuery: '根室花まる 札幌 JRタワー',
    featured: true,
    highlight: '行列の絶えない人気回転寿司',
  },
  {
    id: 's3',
    category: 'seafood',
    name: 'すし善（本店）',
    nameEn: 'Sushizen',
    description: '札幌を代表する江戸前寿司の名店。四季折々の北海道産食材を使った繊細な一品はまさに芸術。接待・記念日に最適。',
    address: '札幌市中央区北1条西27丁目',
    nearest: '地下鉄東西線「円山公園」駅',
    hours: '12:00〜14:00、17:00〜22:00',
    closed: '月曜',
    budget: '10,000円〜',
    rating: 5,
    tags: ['江戸前寿司', '高級', '記念日', '北海道食材'],
    mapQuery: 'すし善 札幌 本店',
    featured: false,
  },
  {
    id: 's4',
    category: 'seafood',
    name: '北のグルメ亭',
    nameEn: 'Kita no Gourmet-tei',
    description: '二条市場内にある食堂。朝から新鮮な海鮮丼が食べられる。ウニ・イクラ・サーモンの豪華三食丼は必食！',
    address: '札幌市中央区南3条東1丁目（二条市場内）',
    nearest: '地下鉄東西線「バスセンター前」駅',
    hours: '7:30〜15:00',
    closed: '不定休',
    budget: '1,500〜4,000円',
    rating: 4,
    tags: ['海鮮丼', '朝食', '二条市場', 'ウニ', 'イクラ'],
    mapQuery: '北のグルメ亭 札幌 二条市場',
    featured: false,
  },
  {
    id: 's5',
    category: 'seafood',
    name: '海鮮処 函太郎 札幌本店',
    nameEn: 'Kaitai-sho Kantaro',
    description: '港町・函館の新鮮な魚介を札幌で楽しめる寿司店。リーズナブルな価格ながらネタが大ぶりで食べ応え十分。',
    address: '札幌市中央区南2条西5丁目 21ビル6F',
    nearest: '地下鉄東西線「大通」駅',
    hours: '11:00〜22:30',
    closed: '年中無休',
    budget: '1,500〜3,000円',
    rating: 4,
    tags: ['寿司', '函館', 'コスパ', 'ランチ'],
    mapQuery: '函太郎 札幌',
    featured: false,
  },

  // ===== SOUP CURRY =====
  {
    id: 'sc1',
    category: 'soup-curry',
    name: 'ガラク',
    nameEn: 'Garaku',
    description: '大通公園近くにある行列の絶えない名店。スープの種類は約15種類、辛さも自由にカスタマイズできる。北海道産野菜がたっぷり。',
    address: '札幌市中央区南2条西2丁目 6-1 地下1F',
    nearest: '地下鉄東西線「大通」駅',
    hours: '11:30〜22:00（スープなくなり次第終了）',
    closed: '不定休',
    budget: '1,000〜2,000円',
    rating: 5,
    tags: ['スープカレー', '大通', '行列', '野菜たっぷり'],
    mapQuery: 'ガラク スープカレー 札幌',
    featured: true,
    highlight: '札幌スープカレーの最高峰',
  },
  {
    id: 'sc2',
    category: 'soup-curry',
    name: 'Suage+（スアゲプラス）',
    nameEn: 'Suage Plus',
    description: 'スープカレーの名店「スアゲ」の2号店。揚げた野菜と旨みたっぷりのスープが絶品。11種類のスープから選べる。',
    address: '札幌市中央区南1条西2丁目 ニュー北星ビルB1F',
    nearest: '地下鉄東西線「大通」駅',
    hours: '11:30〜15:00、17:30〜21:30',
    closed: '火曜',
    budget: '1,200〜2,000円',
    rating: 4,
    tags: ['スープカレー', '揚げ野菜', 'カスタマイズ'],
    mapQuery: 'スアゲプラス スープカレー 札幌',
    featured: false,
  },
  {
    id: 'sc3',
    category: 'soup-curry',
    name: '曼荼羅',
    nameEn: 'Mandara',
    description: 'スープカレー発祥の一説もある老舗。ベジタリアンメニューも充実。スパイスの奥深さを体験できる。',
    address: '札幌市中央区南4条西5丁目 狸小路5丁目',
    nearest: '地下鉄南北線「すすきの」駅',
    hours: '11:30〜21:00',
    closed: '不定休',
    budget: '1,000〜1,500円',
    rating: 4,
    tags: ['老舗', 'ベジタリアン', 'スパイス'],
    mapQuery: '曼荼羅 スープカレー 札幌',
    featured: false,
  },

  // ===== OTHER GOURMET =====
  {
    id: 'g1',
    category: 'gourmet',
    name: '六花亭 札幌本店（喫茶室）',
    nameEn: 'Rokkatei Sapporo Main Store',
    description: '北海道銘菓の老舗・六花亭の喫茶室。バターサンド・マルセイバターケーキなどの名菓とコーヒーの朝食セットが人気。',
    address: '札幌市中央区北4条西6丁目3-3',
    nearest: 'JR「札幌」駅',
    hours: '10:00〜17:30（カフェは11:00〜）',
    closed: '不定休',
    budget: '〜1,500円',
    rating: 4,
    tags: ['朝食', 'ブランチ', 'カフェ', '老舗'],
    mapQuery: '六花亭 札幌本店',
    featured: true,
    highlight: '北海道みやげの定番店でモーニング',
  },
  {
    id: 'g2',
    category: 'gourmet',
    name: 'スープカレーとジンギスカン ソラ',
    nameEn: 'Sola',
    description: '北海道の名物グルメをひとつの店で体験できるユニークなコンセプトの店。地元食材にこだわったメニューが揃う。',
    address: '札幌市中央区南4条西4丁目',
    nearest: '地下鉄南北線「すすきの」駅',
    hours: '11:30〜22:00',
    closed: '水曜',
    budget: '1,500〜3,000円',
    rating: 3,
    tags: ['ジンギスカン', 'スープカレー', '地元食材'],
    mapQuery: 'スープカレーとジンギスカン ソラ 札幌',
    featured: false,
  },
  {
    id: 'g3',
    category: 'gourmet',
    name: 'みよしの',
    nameEn: 'Miyoshino',
    description: '餃子カレーが名物のB級グルメの聖地。餃子とカレーを合わせたユニークな一品は札幌独自のグルメ文化。',
    address: '札幌市中央区大通西4丁目',
    nearest: '地下鉄東西線「大通」駅',
    hours: '11:00〜22:00',
    closed: '年中無休',
    budget: '〜800円',
    rating: 3,
    tags: ['餃子カレー', 'B級グルメ', 'ご当地', '安い'],
    mapQuery: 'みよしの 餃子カレー 札幌',
    featured: false,
  },

  // ===== CAFE =====
  {
    id: 'c1',
    category: 'cafe',
    name: '森彦（MORIHICO.）本店',
    nameEn: 'Morihico Main Store',
    description: '1996年創業、大正時代の古民家を改装した隠れ家カフェ。こだわりのコーヒーと静寂な空間で至福のひと時。',
    address: '札幌市中央区南2条西26丁目2-18',
    nearest: '地下鉄東西線「円山公園」駅',
    hours: '10:00〜21:00（LO 20:30）',
    closed: '年中無休',
    budget: '800〜1,500円',
    rating: 5,
    tags: ['古民家カフェ', '円山', 'コーヒー', '隠れ家'],
    mapQuery: '森彦 MORIHICO 本店 札幌',
    featured: true,
    highlight: '大正の古民家で楽しむ特別なコーヒー',
  },
  {
    id: 'c2',
    category: 'cafe',
    name: '丸美珈琲店',
    nameEn: 'Marumi Coffee',
    description: '自家焙煎にこだわる珈琲専門店。世界中から厳選した豆をその場で焙煎。豆の個性を活かした一杯が楽しめる。',
    address: '札幌市中央区南1条西17丁目',
    nearest: '地下鉄東西線「西18丁目」駅',
    hours: '10:00〜20:00',
    closed: '月曜',
    budget: '600〜1,200円',
    rating: 4,
    tags: ['自家焙煎', 'スペシャルティ', 'コーヒー専門'],
    mapQuery: '丸美珈琲店 札幌',
    featured: false,
  },
  {
    id: 'c3',
    category: 'cafe',
    name: 'ATELIER Morihiko（アトリエモリヒコ）',
    nameEn: 'Atelier Morihiko',
    description: '森彦グループの旗艦店。本格的なコーヒーのほか、バリスタによる丁寧な一杯と食事が楽しめる広々とした空間。',
    address: '札幌市中央区南9条西3丁目 1-6',
    nearest: '地下鉄南北線「中島公園」駅',
    hours: '10:00〜22:00',
    closed: '年中無休',
    budget: '800〜2,000円',
    rating: 4,
    tags: ['バリスタ', '食事', 'おしゃれ', 'ランチ'],
    mapQuery: 'アトリエモリヒコ 札幌',
    featured: false,
  },
  {
    id: 'c4',
    category: 'cafe',
    name: '鳥の木珈琲',
    nameEn: 'Torinoki Coffee',
    description: '円山エリアに佇む小さな珈琲店。週替わりのシングルオリジンコーヒーとフードのペアリングが話題。落ち着いた空間で読書にも最適。',
    address: '札幌市中央区南2条西27丁目',
    nearest: '地下鉄東西線「円山公園」駅',
    hours: '9:00〜19:00',
    closed: '火曜・水曜',
    budget: '700〜1,200円',
    rating: 4,
    tags: ['シングルオリジン', '円山', '静か', '読書'],
    mapQuery: '鳥の木珈琲 札幌',
    featured: false,
  },
  {
    id: 'c5',
    category: 'cafe',
    name: 'Baristart Coffee（バリスタートコーヒー）',
    nameEn: 'Baristart Coffee',
    description: '北海道産牛乳・乳製品を使ったラテが絶品。インスタ映えするラテアートと、北海道の恵みを感じる特別な一杯を。',
    address: '札幌市中央区南1条西1丁目 大丸藤井セントラル前',
    nearest: '地下鉄東西線「大通」駅',
    hours: '8:00〜19:00',
    closed: '年中無休',
    budget: '600〜1,500円',
    rating: 4,
    tags: ['ラテアート', '北海道牛乳', 'インスタ映え', '行列'],
    mapQuery: 'Baristart Coffee 札幌',
    featured: true,
    highlight: '北海道産ミルクのラテが絶品',
  },

  // ===== WESTERN SWEETS =====
  {
    id: 'sw1',
    category: 'sweets-western',
    name: '六花亭',
    nameEn: 'Rokkatei',
    description: '北海道を代表する菓子メーカー。「マルセイバターサンド」「ホワイトチョコレート」などは定番のお土産。全道に店舗があり手軽に購入できる。',
    address: '札幌市中央区北4条西6丁目3-3（札幌本店）',
    nearest: 'JR「札幌」駅',
    hours: '10:00〜18:00（カフェは〜17:30）',
    closed: '不定休',
    budget: '〜3,000円（お土産）',
    rating: 5,
    tags: ['お土産', 'バターサンド', '定番', 'チョコレート'],
    mapQuery: '六花亭 札幌本店',
    featured: true,
    highlight: '北海道みやげの王道',
  },
  {
    id: 'sw2',
    category: 'sweets-western',
    name: '白い恋人パーク（石屋製菓）',
    nameEn: 'Shiroi Koibito Park',
    description: '北海道最大のチョコレート菓子「白い恋人」の石屋製菓が運営するテーマパーク。工場見学・カフェ・お土産ショップが充実。',
    address: '札幌市西区宮の沢2条2丁目11-36',
    nearest: '地下鉄東西線「宮の沢」駅',
    hours: '9:00〜18:00',
    closed: '不定休（要確認）',
    budget: '入場600〜700円',
    rating: 4,
    tags: ['テーマパーク', '白い恋人', '工場見学', 'お土産'],
    mapQuery: '白い恋人パーク 札幌',
    featured: true,
    highlight: '北海道No.1みやげの工場へ',
  },
  {
    id: 'sw3',
    category: 'sweets-western',
    name: 'きのとや（大丸札幌店）',
    nameEn: 'Kinotoya',
    description: '北海道産素材にこだわった洋菓子店。ソフトクリームとチーズタルトが特に人気。直営カフェでスイーツを楽しむこともできる。',
    address: '札幌市中央区北5条西4丁目7 大丸札幌店B1F',
    nearest: 'JR「札幌」駅直結',
    hours: '10:00〜20:00',
    closed: '年中無休',
    budget: '〜2,000円',
    rating: 4,
    tags: ['チーズタルト', 'ソフトクリーム', 'お土産', '北海道産'],
    mapQuery: 'きのとや 大丸札幌',
    featured: false,
  },
  {
    id: 'sw4',
    category: 'sweets-western',
    name: '北菓楼 札幌本館',
    nameEn: 'Kitakaro Sapporo',
    description: '安藤忠雄設計の旧北海道庁立図書館をリノベした建物が印象的。バウムクーヘンとシュークリームがヒット商品。カフェも併設。',
    address: '札幌市中央区北1条西5丁目',
    nearest: '地下鉄東西線「大通」駅',
    hours: '9:30〜18:00',
    closed: '年中無休',
    budget: '〜2,000円',
    rating: 4,
    tags: ['バウムクーヘン', '安藤忠雄', '旧図書館', 'カフェ'],
    mapQuery: '北菓楼 札幌本館',
    featured: true,
    highlight: '安藤忠雄設計の歴史的建物でスイーツを',
  },
  {
    id: 'sw5',
    category: 'sweets-western',
    name: 'ルタオ（LeTAO）本店',
    nameEn: 'LeTAO',
    description: '小樽発の洋菓子ブランド。「ドゥーブルフロマージュ」は北海道で最も有名なチーズケーキのひとつ。札幌にも複数店舗あり。',
    address: '札幌市中央区大通西4丁目 札幌大丸B1F・他',
    nearest: '地下鉄東西線「大通」駅',
    hours: '店舗により異なる',
    closed: '年中無休',
    budget: '〜3,000円',
    rating: 4,
    tags: ['チーズケーキ', '小樽', 'お土産', '人気'],
    mapQuery: 'ルタオ 札幌',
    featured: false,
  },

  // ===== JAPANESE SWEETS =====
  {
    id: 'sj1',
    category: 'sweets-japanese',
    name: '柳月（Ryugetsu）',
    nameEn: 'Ryugetsu',
    description: '北海道産の食材を使った和洋菓子の名店。「三方六（さんぽうろく）」は白樺の木肌を模した人気のバウムクーヘン。',
    address: '札幌市中央区北3条西2丁目 大丸札幌内・各所',
    nearest: 'JR「札幌」駅',
    hours: '10:00〜20:00（店舗により異なる）',
    closed: '年中無休',
    budget: '〜3,000円',
    rating: 4,
    tags: ['三方六', 'バウムクーヘン', 'お土産', '和洋菓子'],
    mapQuery: '柳月 札幌',
    featured: true,
    highlight: '白樺を模した「三方六」が有名',
  },
  {
    id: 'sj2',
    category: 'sweets-japanese',
    name: '清月',
    nameEn: 'Seigetsu',
    description: '創業70年以上の老舗和菓子店。どら焼き・最中など、丁寧に作られた季節の和菓子が揃う。お土産にも喜ばれる一品。',
    address: '札幌市中央区南1条西5丁目 時計台近く',
    nearest: '地下鉄東西線「大通」駅',
    hours: '9:30〜18:30',
    closed: '日曜',
    budget: '〜2,000円',
    rating: 4,
    tags: ['どら焼き', '最中', '老舗', '季節の和菓子'],
    mapQuery: '清月 和菓子 札幌',
    featured: false,
  },
  {
    id: 'sj3',
    category: 'sweets-japanese',
    name: '美園（Misono）',
    nameEn: 'Misono',
    description: '昭和25年創業の老舗。北海道産小豆を使った上品なあんこと、風味豊かな和菓子が揃う。茶室で抹茶と和菓子のセットもある。',
    address: '札幌市豊平区美園8条1丁目',
    nearest: '地下鉄東豊線「美園」駅',
    hours: '9:30〜18:00',
    closed: '月曜',
    budget: '〜1,500円',
    rating: 4,
    tags: ['老舗', '北海道産小豆', '抹茶', '茶室'],
    mapQuery: '美園 和菓子 札幌',
    featured: false,
  },
  {
    id: 'sj4',
    category: 'sweets-japanese',
    name: '北海道神宮茶屋',
    nameEn: 'Hokkaido Jingu Chaya',
    description: '北海道神宮の参道沿いに佇む甘味処。名物の「開拓おかき」や草餅など神宮ゆかりの和菓子が楽しめる。桜の季節は特に混み合う。',
    address: '札幌市中央区宮ヶ丘474（北海道神宮境内）',
    nearest: '地下鉄東西線「円山公園」駅',
    hours: '9:00〜17:00',
    closed: '不定休',
    budget: '〜800円',
    rating: 4,
    tags: ['神宮', '草餅', '参道', '桜', '観光'],
    mapQuery: '北海道神宮茶屋 札幌',
    featured: false,
  },

  // ===== CRAFTS & SOUVENIRS =====
  {
    id: 'cr1',
    category: 'crafts',
    name: 'ニポポ民芸品店',
    nameEn: 'Nipopo Folk Art',
    description: 'アイヌ文化に根ざした木彫り人形「ニポポ」をはじめ、北海道の民芸品が揃う老舗の土産物店。一点物の木彫り品も多い。',
    address: '札幌市中央区南3条西4丁目 狸小路4丁目',
    nearest: '地下鉄東西線「大通」駅',
    hours: '10:00〜19:00',
    closed: '不定休',
    budget: '〜10,000円',
    rating: 3,
    tags: ['アイヌ', '木彫り', '民芸品', '狸小路'],
    mapQuery: 'ニポポ 民芸品 札幌',
    featured: false,
  },
  {
    id: 'cr2',
    category: 'crafts',
    name: '北海道アルタ（大丸内）',
    nameEn: 'Hokkaido Alta',
    description: '北海道産の食品・工芸品・雑貨を幅広く揃えるセレクトショップ。地元デザイナーによる小物や、道産子の間で人気のブランドも多数。',
    address: '札幌市中央区北5条西4丁目 大丸札幌B2F',
    nearest: 'JR「札幌」駅直結',
    hours: '10:00〜20:00',
    closed: '年中無休',
    budget: '1,000〜20,000円',
    rating: 4,
    tags: ['北海道産', 'セレクトショップ', 'お土産', 'デザイン雑貨'],
    mapQuery: '北海道アルタ 大丸札幌',
    featured: false,
  },
  {
    id: 'cr3',
    category: 'crafts',
    name: 'ウポポイ 民族共生象徴空間（関連土産）',
    nameEn: 'Upopoy Related Goods',
    description: '道内各地で購入できるウポポイ公認グッズ。アイヌの伝統文様をモチーフにしたアクセサリー・テキスタイルは特別なお土産に最適。',
    address: 'JRタワー内・大丸内各所',
    nearest: 'JR「札幌」駅',
    hours: '10:00〜20:00',
    closed: '年中無休',
    budget: '1,000〜30,000円',
    rating: 4,
    tags: ['アイヌ文化', '公認グッズ', '伝統文様', '特別'],
    mapQuery: 'ウポポイ 土産 札幌',
    featured: true,
    highlight: 'アイヌ文化を持ち帰ろう',
  },
  {
    id: 'cr4',
    category: 'crafts',
    name: 'プロペラカフェ（Propeller Cafe）',
    nameEn: 'Propeller Cafe',
    description: '丘珠空港近くの複合施設。地元クリエイターの手作り雑貨・アート作品が集まるマーケットやショップが充実。不定期イベントも多数。',
    address: '札幌市東区丘珠町592',
    nearest: '地下鉄東豊線「栄町」駅からバス',
    hours: '11:00〜18:00',
    closed: '月〜水曜',
    budget: '〜5,000円',
    rating: 3,
    tags: ['クリエイター', '手作り雑貨', 'アート', 'マーケット'],
    mapQuery: 'プロペラカフェ 札幌',
    featured: false,
  },

  // ===== UNIQUE SHOPS =====
  {
    id: 'us1',
    category: 'unique-shops',
    name: '狸小路商店街',
    nameEn: 'Tanuki-koji Shopping Street',
    description: '1869年創業の老舗アーケード商店街。薬局・衣料・食料品・飲食店まで約180店舗が1〜7丁目に連なる。雨の日も安心してショッピングできる。',
    address: '札幌市中央区南2・3条西1〜7丁目',
    nearest: '地下鉄南北線「すすきの」駅 / 東西線「大通」駅',
    hours: '店舗により異なる（10:00〜22:00頃）',
    closed: '年中無休',
    budget: '〜5,000円',
    rating: 4,
    tags: ['アーケード', '老舗', 'ショッピング', '観光', '雨の日'],
    mapQuery: '狸小路商店街 札幌',
    featured: true,
    highlight: '1869年から続く老舗アーケード',
  },
  {
    id: 'us2',
    category: 'unique-shops',
    name: 'BOOK OFF 札幌',
    nameEn: 'Bookoff Sapporo',
    description: '旅行者にも人気の中古本・アニメグッズ・ゲームなどが揃うリサイクルショップ。日本の大衆文化を探索するのに最適。',
    address: '札幌市中央区北4条西2丁目',
    nearest: 'JR「札幌」駅',
    hours: '10:00〜22:00',
    closed: '年中無休',
    budget: '〜5,000円',
    rating: 3,
    tags: ['古本', 'アニメ', 'ゲーム', '中古', 'ポップカルチャー'],
    mapQuery: 'ブックオフ 札幌 北4条',
    featured: false,
  },
  {
    id: 'us3',
    category: 'unique-shops',
    name: 'サッポロファクトリー',
    nameEn: 'Sapporo Factory',
    description: '旧サッポロビール工場をリノベした複合商業施設。ガラスのドームアトリウムが印象的で、ショッピング・グルメ・映画館が揃う。',
    address: '札幌市中央区北2条東4丁目',
    nearest: '地下鉄東西線「バスセンター前」駅',
    hours: '10:00〜20:00',
    closed: '年中無休',
    budget: '〜30,000円',
    rating: 4,
    tags: ['ショッピング', '映画', '旧工場', 'リノベ', 'ドーム'],
    mapQuery: 'サッポロファクトリー',
    featured: false,
  },
  {
    id: 'us4',
    category: 'unique-shops',
    name: '円山西町の古道具・雑貨通り',
    nameEn: 'Maruyama Antiques Street',
    description: '円山エリアに点在するアンティーク・ヴィンテージ雑貨のお店群。昭和レトロな家具・食器・古着などを扱う個性的な店が集まる。',
    address: '札幌市中央区円山西町周辺',
    nearest: '地下鉄東西線「円山公園」駅',
    hours: '店舗により異なる（11:00〜18:00頃）',
    closed: '店舗により異なる',
    budget: '〜10,000円',
    rating: 4,
    tags: ['アンティーク', 'ヴィンテージ', '古着', '雑貨', '円山'],
    mapQuery: '円山 アンティーク 雑貨 札幌',
    featured: false,
  },

  // ===== SIGHTSEEING =====
  {
    id: 'sg1',
    category: 'sightseeing',
    name: '札幌時計台',
    nameEn: 'Sapporo Clock Tower',
    description: '1878年建設の北海道大学農学部演武場が起源。日本三大がっかりスポットとも言われるが、夜はライトアップされて美しい歴史的建造物。',
    address: '札幌市中央区北1条西2丁目',
    nearest: '地下鉄東西線「大通」駅',
    hours: '8:45〜17:10（月曜定休）',
    closed: '月曜・年末年始',
    budget: '入場200円',
    rating: 4,
    tags: ['歴史的建造物', '定番', '観光', '写真スポット', '夜景'],
    mapQuery: '札幌時計台',
    featured: true,
    highlight: '札幌観光の象徴的ランドマーク',
  },
  {
    id: 'sg2',
    category: 'sightseeing',
    name: '大通公園',
    nameEn: 'Odori Park',
    description: '東西約1.5kmに広がる市民の憩いの公園。雪まつり・ビアガーデン・クリスマスイルミネーションなど年間を通じてイベントが開催される。',
    address: '札幌市中央区大通西1〜13丁目',
    nearest: '地下鉄東西線・南北線「大通」駅',
    hours: '24時間（無料）',
    closed: '年中無休',
    budget: '無料',
    rating: 5,
    tags: ['公園', '無料', 'イベント', '散策', '年中楽しめる'],
    mapQuery: '大通公園 札幌',
    featured: true,
    highlight: '一年中イベントが絶えない街の中心',
  },
  {
    id: 'sg3',
    category: 'sightseeing',
    name: '北海道庁旧本庁舎（赤れんが庁舎）',
    nameEn: 'Former Hokkaido Government Office Building',
    description: '1888年建設のネオバロック様式の赤れんが建築。無料で内部見学ができ、北海道の歴史を学べる展示室も充実。庭園も美しい。',
    address: '札幌市中央区北3条西6丁目',
    nearest: '地下鉄東西線「大通」駅',
    hours: '8:45〜18:00',
    closed: '年末年始・一部時期',
    budget: '無料',
    rating: 4,
    tags: ['赤れんが', '歴史', '無料', '建築', '庭園'],
    mapQuery: '北海道庁旧本庁舎 赤れんが',
    featured: false,
  },
  {
    id: 'sg4',
    category: 'sightseeing',
    name: 'さっぽろテレビ塔',
    nameEn: 'Sapporo TV Tower',
    description: '大通公園の東端に立つ147mの電波塔。展望台からは大通公園と街並みを一望できる。夜のイルミネーションも美しい。',
    address: '札幌市中央区大通西1丁目',
    nearest: '地下鉄東西線「大通」駅',
    hours: '9:00〜22:00（季節により変動）',
    closed: '不定休',
    budget: '展望台700円',
    rating: 4,
    tags: ['展望台', '夜景', '大通公園', '写真スポット'],
    mapQuery: 'さっぽろテレビ塔',
    featured: false,
  },
  {
    id: 'sg5',
    category: 'sightseeing',
    name: '羊ヶ丘展望台',
    nameEn: 'Hitsujigaoka Observation Hill',
    description: 'クラーク博士の像と「Boys, be ambitious!」でお馴染みの展望台。牧草地に羊が放牧され、雄大な北海道の自然が広がる。',
    address: '札幌市豊平区羊ヶ丘1番地',
    nearest: '地下鉄東豊線「福住」駅からバス15分',
    hours: '8:30〜18:00（季節変動）',
    closed: '年中無休',
    budget: '入場600円',
    rating: 4,
    tags: ['クラーク像', '牧草地', '羊', '展望', '写真スポット'],
    mapQuery: '羊ヶ丘展望台 札幌',
    featured: true,
    highlight: 'クラーク博士と記念撮影！',
  },
  {
    id: 'sg6',
    category: 'sightseeing',
    name: '北海道大学キャンパス',
    nameEn: 'Hokkaido University Campus',
    description: 'ポプラ並木・銀杏並木が美しい国立大学のキャンパスは観光地としても人気。秋の黄葉シーズンは特に見事。総合博物館への入場も無料。',
    address: '札幌市北区北8条西5丁目',
    nearest: 'JR「札幌」駅',
    hours: '散策自由（24時間）',
    closed: '年中無休',
    budget: '無料',
    rating: 4,
    tags: ['ポプラ並木', '銀杏', '秋の紅葉', '無料', '散策'],
    mapQuery: '北海道大学 キャンパス',
    featured: false,
  },
  {
    id: 'sg7',
    category: 'sightseeing',
    name: 'もいわ山 展望台',
    nameEn: 'Mt. Moiwa Observatory',
    description: '標高531mのもいわ山頂からは札幌市内を360度見渡せる夜景の名所。ロープウェイとリフトで山頂へ。カップルにも人気。',
    address: '札幌市中央区伏見5丁目',
    nearest: '市電「ロープウェイ入口」停',
    hours: '11:00〜22:00（季節変動）',
    closed: '積雪期は一部時間変動',
    budget: 'ロープウェイ往復2,100円',
    rating: 5,
    tags: ['夜景', '展望台', 'ロープウェイ', 'デート', '360度'],
    mapQuery: 'もいわ山 展望台 札幌',
    featured: true,
    highlight: '「日本新三大夜景都市」の絶景を体感',
  },
  {
    id: 'sg8',
    category: 'sightseeing',
    name: '円山公園・北海道神宮',
    nameEn: 'Maruyama Park & Hokkaido Jingu',
    description: '市民の憩いの場・円山公園と、北海道の総鎮守・北海道神宮が隣接。春の桜は必見。リスや野鳥が生息する豊かな自然も魅力。',
    address: '札幌市中央区宮ヶ丘474（神宮）',
    nearest: '地下鉄東西線「円山公園」駅',
    hours: '散策自由 / 神宮：7:00〜17:00頃',
    closed: '年中無休',
    budget: '無料',
    rating: 4,
    tags: ['桜', '自然', '神社', '散策', '無料', 'リス'],
    mapQuery: '北海道神宮 円山公園',
    featured: false,
  },

  // ===== ONSEN =====
  {
    id: 'o1',
    category: 'onsen',
    name: '定山渓温泉',
    nameEn: 'Jozankei Onsen',
    description: '札幌市内から約1時間の温泉郷。渓谷沿いに旅館・ホテルが立ち並び、秘湯感あふれる露天風呂が人気。日帰り入浴も可能な施設多数。',
    address: '札幌市南区定山渓',
    nearest: '札幌駅・すすきのからバス約70分',
    hours: '施設により異なる（日帰り：10:00〜21:00頃）',
    closed: '施設により異なる',
    budget: '日帰り：1,000〜2,000円 / 宿泊：15,000円〜',
    rating: 5,
    tags: ['温泉郷', '露天風呂', '渓谷', '日帰り可', '宿泊'],
    mapQuery: '定山渓温泉 札幌',
    featured: true,
    highlight: '「札幌の奥座敷」と呼ばれる名湯',
  },
  {
    id: 'o2',
    category: 'onsen',
    name: '豊平峡温泉',
    nameEn: 'Hoheikyo Onsen',
    description: '定山渓の奥に位置する本格的なインド料理も楽しめる温泉施設。100%源泉かけ流しの野天風呂が有名。カレーと温泉のセットが人気。',
    address: '札幌市南区定山渓608',
    nearest: '定山渓温泉からバスで10分',
    hours: '10:00〜22:30',
    closed: '年中無休',
    budget: '入浴1,100円',
    rating: 4,
    tags: ['源泉かけ流し', '野天風呂', 'カレー', '定山渓'],
    mapQuery: '豊平峡温泉',
    featured: false,
  },
  {
    id: 'o3',
    category: 'onsen',
    name: '小金湯温泉',
    nameEn: 'Koganeyu Onsen',
    description: '豊平川沿いに佇む日帰り温泉施設。ナトリウム・塩化物泉の茶褐色の湯が特徴で、保温・保湿効果が高い。リーズナブルで地元客にも人気。',
    address: '札幌市南区小金湯25',
    nearest: '地下鉄真駒内駅からバス25分',
    hours: '10:00〜22:00',
    closed: '第3月曜',
    budget: '入浴700〜800円',
    rating: 3,
    tags: ['日帰り', 'リーズナブル', '茶褐色の湯', '保温効果'],
    mapQuery: '小金湯温泉',
    featured: false,
  },
  {
    id: 'o4',
    category: 'onsen',
    name: '定山渓鶴雅リゾートスパ森の謌',
    nameEn: 'Jozankei Tsuruga Resort Spa Mori no Uta',
    description: '定山渓の最高峰ラグジュアリーリゾート。「究極の温泉」「美食」「自然」が融合した贅沢な滞在体験。露天風呂付き客室も充実。',
    address: '札幌市南区定山渓温泉東3丁目',
    nearest: '札幌駅から送迎バスあり',
    hours: '宿泊施設（日帰りは要問合せ）',
    closed: '年中無休',
    budget: '30,000〜80,000円/人（1泊2食）',
    rating: 5,
    tags: ['高級旅館', '露天風呂', 'ラグジュアリー', '美食', '記念日'],
    mapQuery: '定山渓鶴雅リゾート 森の謌',
    featured: true,
    highlight: '北海道最上級の温泉リゾート',
  },

  // ===== AMUSEMENT =====
  {
    id: 'am1',
    category: 'amusement',
    name: 'モエレ沼公園',
    nameEn: 'Moerenuma Park',
    description: '彫刻家イサム・ノグチが設計した芸術公園。廃棄物処理場の跡地が美しいアート空間に変貌。ガラスのピラミッドは特に印象的。',
    address: '札幌市東区モエレ沼公園1-1',
    nearest: '地下鉄東豊線「環状通東」駅からバス20分',
    hours: '7:00〜22:00',
    closed: '第2・第4火曜',
    budget: '無料（ガラスのピラミッド内は一部有料）',
    rating: 5,
    tags: ['イサム・ノグチ', 'アート', '無料', '自然', 'ガラスのピラミッド'],
    mapQuery: 'モエレ沼公園 札幌',
    featured: true,
    highlight: 'イサム・ノグチが設計した世界的アート公園',
  },
  {
    id: 'am2',
    category: 'amusement',
    name: 'サッポロビール博物館',
    nameEn: 'Sapporo Beer Museum',
    description: '明治の赤レンガ建築の中にある日本最古のビール博物館（無料）。ビールの歴史を学んだ後は有料の試飲ができる。',
    address: '札幌市東区北7条東9丁目1-1',
    nearest: 'JR「苗穂」駅 / 地下鉄から路線バスも可',
    hours: '11:00〜18:00',
    closed: '月曜（祝日の場合は翌日）',
    budget: '入場無料（試飲は有料）',
    rating: 4,
    tags: ['博物館', 'ビール', '赤レンガ', '無料', '試飲'],
    mapQuery: 'サッポロビール博物館',
    featured: false,
  },
  {
    id: 'am3',
    category: 'amusement',
    name: '北海道開拓の村',
    nameEn: 'Historical Village of Hokkaido',
    description: '明治〜昭和初期の建物を移築・復元した野外博物館。52棟の建物が広大な敷地に並び、馬車や人力車での移動も楽しめる。',
    address: '札幌市厚別区厚別町小野幌50-1',
    nearest: 'JR「野幌」駅からバス10分',
    hours: '9:00〜17:00',
    closed: '月曜（夏季は無休）',
    budget: '入場800円',
    rating: 4,
    tags: ['野外博物館', '明治', '開拓時代', '馬車', '歴史'],
    mapQuery: '北海道開拓の村',
    featured: false,
  },
  {
    id: 'am4',
    category: 'amusement',
    name: '円山動物園',
    nameEn: 'Maruyama Zoo',
    description: '1951年開園の市立動物園。ホッキョクグマ・シロフクロウなど北海道の動物が充実。子どもはもちろん大人にも人気のスポット。',
    address: '札幌市中央区宮ヶ丘3-1',
    nearest: '地下鉄東西線「円山公園」駅からバス5分',
    hours: '9:00〜17:00（季節変動）',
    closed: '月曜（祝日の場合は翌日）',
    budget: '入場600円',
    rating: 4,
    tags: ['動物園', 'ホッキョクグマ', 'ファミリー', '円山'],
    mapQuery: '円山動物園 札幌',
    featured: false,
  },
  {
    id: 'am5',
    category: 'amusement',
    name: 'ノルベサ（Norbesa）観覧車',
    nameEn: 'Norbesa Ferris Wheel',
    description: 'すすきのの複合商業施設「ノルベサ」屋上にある観覧車。夜の札幌の夜景を楽しみながら空中散歩。すすきのの繁華街のど真ん中で乗れる。',
    address: '札幌市中央区南3条西5丁目',
    nearest: '地下鉄南北線「すすきの」駅',
    hours: '12:00〜23:00',
    closed: '年中無休',
    budget: '600円',
    rating: 3,
    tags: ['観覧車', '夜景', 'すすきの', 'デート', 'ナイトビュー'],
    mapQuery: 'ノルベサ 観覧車 すすきの',
    featured: false,
  },
  {
    id: 'am6',
    category: 'amusement',
    name: '北海道博物館',
    nameEn: 'Hokkaido Museum',
    description: '北海道の自然・歴史・文化を総合的に紹介する道立博物館。アイヌ文化の展示も充実。子どもから大人まで楽しめる。野幌森林公園内に位置する。',
    address: '札幌市厚別区厚別町小野幌53-2',
    nearest: 'JR「野幌」駅からバス',
    hours: '9:30〜17:00',
    closed: '月曜（夏季は無休）',
    budget: '入場600円',
    rating: 4,
    tags: ['博物館', 'アイヌ', '北海道の自然', '歴史', 'ファミリー'],
    mapQuery: '北海道博物館',
    featured: false,
  },

  // ===== ACCOMMODATION =====
  {
    id: 'ac1',
    category: 'accommodation',
    name: 'JRタワーホテル日航札幌',
    nameEn: 'JR Tower Hotel Nikko Sapporo',
    description: 'JR札幌駅直結の超高層タワーホテル。22〜34Fの客室から札幌の夜景を一望できる。アクセス抜群で観光・ビジネスのどちらにも最適。',
    address: '札幌市中央区北5条西2丁目 JRタワー内',
    nearest: 'JR「札幌」駅直結',
    hours: 'チェックイン15:00 / アウト12:00',
    closed: '年中無休',
    budget: '15,000〜50,000円/室',
    rating: 5,
    tags: ['高級', 'JR直結', '夜景', '利便性', 'スパ'],
    mapQuery: 'JRタワーホテル日航札幌',
    featured: true,
    highlight: '駅直結で北海道観光の拠点に最適',
  },
  {
    id: 'ac2',
    category: 'accommodation',
    name: 'ANAクラウンプラザホテル札幌',
    nameEn: 'ANA Crowne Plaza Sapporo',
    description: '札幌の中心地・大通公園に面した国際的なラグジュアリーホテル。スタイリッシュな客室とレストランが充実。観光・ショッピングに便利。',
    address: '札幌市中央区北3条西1丁目2',
    nearest: '地下鉄東西線「大通」駅',
    hours: 'チェックイン14:00 / アウト12:00',
    closed: '年中無休',
    budget: '15,000〜40,000円/室',
    rating: 4,
    tags: ['高級', '大通公園', '国際的', 'スタイリッシュ'],
    mapQuery: 'ANAクラウンプラザホテル札幌',
    featured: false,
  },
  {
    id: 'ac3',
    category: 'accommodation',
    name: 'センチュリーロイヤルホテル',
    nameEn: 'Century Royal Hotel Sapporo',
    description: '札幌駅から徒歩3分。高層ホテルの客室からは円山・大倉山ジャンプ競技場まで見渡せる。コスパが高くリピーターも多い。',
    address: '札幌市中央区北5条西5丁目2',
    nearest: 'JR「札幌」駅',
    hours: 'チェックイン15:00 / アウト11:00',
    closed: '年中無休',
    budget: '10,000〜30,000円/室',
    rating: 4,
    tags: ['コスパ', '観光拠点', '夜景', 'ビジネス'],
    mapQuery: 'センチュリーロイヤルホテル 札幌',
    featured: false,
  },
  {
    id: 'ac4',
    category: 'accommodation',
    name: 'ホテルモントレエーデルホフ札幌',
    nameEn: 'Hotel Monterey Edelhof Sapporo',
    description: 'ウィーンをテーマにしたデザインホテル。大通公園に面し観光に最適のロケーション。落ち着いた内装と清潔感ある客室が魅力。',
    address: '札幌市中央区北2条西1丁目4',
    nearest: '地下鉄東西線「大通」駅',
    hours: 'チェックイン14:00 / アウト11:00',
    closed: '年中無休',
    budget: '8,000〜25,000円/室',
    rating: 4,
    tags: ['ウィーン', 'デザイン', '大通', 'コスパ'],
    mapQuery: 'ホテルモントレエーデルホフ 札幌',
    featured: false,
  },
  {
    id: 'ac5',
    category: 'accommodation',
    name: '定山渓鶴雅リゾートスパ（宿泊）',
    nameEn: 'Jozankei Tsuruga Resort',
    description: '定山渓随一の高級温泉旅館。全室に天然温泉が引かれ、贅を尽くした客室と北海道食材の料理が自慢。特別な旅に最適。',
    address: '札幌市南区定山渓温泉東3丁目',
    nearest: '札幌駅から送迎バスあり',
    hours: 'チェックイン15:00 / アウト11:00',
    closed: '年中無休',
    budget: '30,000〜80,000円/人（1泊2食）',
    rating: 5,
    tags: ['高級旅館', '温泉', '懐石料理', '特別な旅', '記念日'],
    mapQuery: '定山渓鶴雅リゾート',
    featured: true,
    highlight: '最高の温泉と美食で贅沢な一夜を',
  },
  {
    id: 'ac6',
    category: 'accommodation',
    name: 'ドーミーイン PREMIUM 札幌',
    nameEn: 'Dormy Inn Premium Sapporo',
    description: '天然温泉大浴場付きのビジネスホテル。すすきのすぐそばで観光・グルメに便利。コスパ最高で清潔感抜群のため旅行者に大人気。',
    address: '札幌市中央区南4条西5丁目',
    nearest: '地下鉄南北線「すすきの」駅',
    hours: 'チェックイン15:00 / アウト11:00',
    closed: '年中無休',
    budget: '6,000〜15,000円/室',
    rating: 4,
    tags: ['温泉大浴場', 'コスパ', 'すすきの', 'ビジネスホテル', '旅行者に人気'],
    mapQuery: 'ドーミーイン PREMIUM 札幌',
    featured: false,
  },

  // ===== SEASONAL EVENTS =====
  {
    id: 'ev1',
    category: 'events',
    name: 'さっぽろ雪まつり',
    nameEn: 'Sapporo Snow Festival',
    description: '毎年2月に開催される世界的な冬のビッグイベント。大通公園・すすきの・つどーむ会場に巨大な雪像・氷像が立ち並ぶ。1950年の初開催から世界中の観光客を魅了。',
    address: '大通公園・すすきの・つどーむ会場',
    nearest: '地下鉄東西線「大通」駅ほか',
    hours: '10:00〜22:00（会場により変動）',
    closed: 'イベント期間中は無休',
    budget: '無料',
    rating: 5,
    tags: ['2月', '雪像', '冬', '無料', '世界的イベント', '定番'],
    mapQuery: 'さっぽろ雪まつり 大通会場',
    featured: true,
    highlight: '世界三大雪まつりのひとつ！必見',
    season: '冬（2月）',
  },
  {
    id: 'ev2',
    category: 'events',
    name: 'YOSAKOIソーラン祭り',
    nameEn: 'YOSAKOI Soran Festival',
    description: '毎年6月に開催される北海道の夏を告げる祭り。全国から約300チーム・33,000人が参加し、大通公園・市内各所で勇壮な踊りを披露。',
    address: '大通公園・市内各所',
    nearest: '地下鉄東西線「大通」駅',
    hours: '9:00〜21:00頃',
    closed: 'イベント期間中は無休',
    budget: '無料（一部有料エリアあり）',
    rating: 4,
    tags: ['6月', 'よさこい', '踊り', '祭り', '無料'],
    mapQuery: 'YOSAKOIソーラン祭り 大通公園',
    featured: false,
    season: '初夏（6月）',
  },
  {
    id: 'ev3',
    category: 'events',
    name: '大通公園ビアガーデン',
    nameEn: 'Odori Park Beer Garden',
    description: '7〜8月に開催される日本最大級のビアガーデン。各ビールメーカーが集結し、約1km以上にわたるビールとジンギスカンの祭典。',
    address: '大通公園 2〜10丁目',
    nearest: '地下鉄東西線「大通」駅',
    hours: '12:00〜21:00頃',
    closed: 'イベント期間中は無休',
    budget: '1,000〜3,000円',
    rating: 5,
    tags: ['7〜8月', 'ビール', 'ジンギスカン', '夏', '大規模'],
    mapQuery: '大通公園ビアガーデン 札幌',
    featured: true,
    highlight: '日本最大のビアガーデンで夏の夜を堪能',
    season: '夏（7〜8月）',
  },
  {
    id: 'ev4',
    category: 'events',
    name: 'さっぽろオータムフェスト',
    nameEn: 'Sapporo Autumn Fest',
    description: '9月〜10月に大通公園で開催される北海道の食の祭典。道内各地のグルメが集まり、新鮮な海産物・農産物をリーズナブルに楽しめる。',
    address: '大通公園 2〜8丁目',
    nearest: '地下鉄東西線「大通」駅',
    hours: '11:00〜21:00頃',
    closed: 'イベント期間中は無休',
    budget: '〜3,000円',
    rating: 5,
    tags: ['9〜10月', 'グルメ', '北海道食材', '食の祭典', '秋'],
    mapQuery: 'さっぽろオータムフェスト 大通公園',
    featured: true,
    highlight: '北海道全土のグルメが大通公園に大集合',
    season: '秋（9〜10月）',
  },
  {
    id: 'ev5',
    category: 'events',
    name: 'さっぽろホワイトイルミネーション',
    nameEn: 'Sapporo White Illumination',
    description: '11月下旬〜2月末まで大通公園・駅前通で開催される光の祭典。100万個以上のLEDが街を彩る、日本最古のイルミネーションイベント。',
    address: '大通公園・駅前通',
    nearest: '地下鉄東西線「大通」駅',
    hours: '17:00〜23:00',
    closed: 'イベント期間中は無休',
    budget: '無料',
    rating: 4,
    tags: ['11〜2月', 'イルミネーション', '冬', '無料', 'ロマンチック'],
    mapQuery: 'さっぽろホワイトイルミネーション',
    featured: false,
    season: '冬（11月〜2月）',
  },
  {
    id: 'ev6',
    category: 'events',
    name: 'さっぽろ春まつり（大通公園の桜）',
    nameEn: 'Sapporo Spring Cherry Blossoms',
    description: '5月上旬〜中旬、大通公園・円山公園・北海道大学などが桜で彩られる。本州より遅い春の訪れとともに、屋台や花見が楽しめる。',
    address: '大通公園・円山公園・北海道大学',
    nearest: '地下鉄東西線「大通」駅 ほか',
    hours: '終日（夜桜も美しい）',
    closed: '期間中無休',
    budget: '無料',
    rating: 4,
    tags: ['5月', '桜', '花見', '春', '無料'],
    mapQuery: '大通公園 桜 札幌',
    featured: false,
    season: '春（4〜5月）',
  },
  {
    id: 'ev7',
    category: 'events',
    name: '北海道マラソン',
    nameEn: 'Hokkaido Marathon',
    description: '毎年8月に開催される日本最大の夏マラソン大会。市内中心部を駆け抜けるフルマラソン。応援・観戦するだけでも街の熱気を感じられる。',
    address: '大通公園スタート・ゴール',
    nearest: '地下鉄東西線「大通」駅',
    hours: '8月下旬 7:00スタート',
    closed: '年1回開催',
    budget: '観戦無料',
    rating: 3,
    tags: ['8月', 'マラソン', 'スポーツ', '観戦', '夏'],
    mapQuery: '北海道マラソン 大通公園',
    featured: false,
    season: '夏（8月）',
  },
  {
    id: 'ev8',
    category: 'events',
    name: '大倉山ジャンプ競技大会',
    nameEn: 'Okurayama Ski Jump Competition',
    description: '1972年札幌冬季オリンピックの会場・大倉山ジャンプ競技場で冬に開催される国際大会。夏はリフトで展望台に上り絶景も楽しめる。',
    address: '札幌市中央区宮の森1274',
    nearest: '地下鉄東西線「円山公園」駅からバス15分',
    hours: '8:30〜21:00（リフト）',
    closed: '不定休',
    budget: 'リフト往復500円 / 競技観戦：要確認',
    rating: 4,
    tags: ['スキージャンプ', 'オリンピック', '展望台', '冬', 'スポーツ'],
    mapQuery: '大倉山ジャンプ競技場 札幌',
    featured: false,
    season: '冬（12〜3月）',
  },
];
